syntax on
colorscheme molokai
set t_Co=256
set number
filetype plugin indent on
au FileType python map <buffer> <F6> :!pep8 %<CR>
au BufRead,BufNewFile /etc/nginx/* set ft=nginx
autocmd FileType python set omnifunc=pythoncomplete#Complete
set expandtab
set textwidth=79
set tabstop=8
set softtabstop=4
set shiftwidth=4
set autoindent
highlight ExtraWhitespace ctermbg=red guibg=red
match ExtraWhitespace /\s\+$/
autocmd BufWinEnter * match ExtraWhitespace /\s\+$/
autocmd InsertEnter * match ExtraWhitespace /\s\+\%#\@<!$/
autocmd InsertLeave * match ExtraWhitespace /\s\+$/
autocmd BufWinLeave * call clearmatches()

" Autocommands {
"      "Python {
       au BufRead,BufNewFile *.py match ErrorMsg '\%>80v.\+'
    "}
"   }

"statusline
set laststatus=2
if has('statusline')
set statusline=%<%f\
set statusline+=%w%h%m%r
set statusline+=%{fugitive#statusline()}
set statusline+=\ [%{&ff}/%Y
set statusline+=\ [%{getcwd()}]
set statusline+=%=%-14.(Line:\ %l\ of\ %L\ [%p%%]\ -\ Col:\ %c%V%)
endif
"

