---
# This role will run the Plone Installer in standalone mode

- name: Untar Installer
  sudo: False
  command: tar -xf Plone-4.3.2-UnifiedInstaller.tgz

- name: Run Installer
  sudo: False
  command: ./Plone-4.3.2-UnifiedInstaller/install.sh standalone

- name: Deleting old files ...
  sudo: False
  command: rm -rf Plone-4.3.2-UnifiedInstaller.tgz

